<svelte:head>
  <title>expect(Exception) Contest Terms & Condition</title>
</svelte:head>

<div>
<h1>Twitter: Win a free eBook</h1>
<h2>Official Rules</h2>
<strong>NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE WILL NOT INCREASE YOUR CHANCES OF WINNING. TRAVEL NOT INCLUDED. ODDS OF WINNING WILL DEPEND ON THE TOTAL NUMBER OF ELIGIBLE ENTRIES RECEIVED. VOID WHERE PROHIBITED BY LAW. ALL DISPUTES WILL BE RESOLVED SOLELY BY BINDING ARBITRATION AND ENTRANTS WAIVE THE ABILITY TO BRING CLAIMS IN A CLASS ACTION FORMAT.</strong>
<p><strong>ELIGIBILITY:</strong> expect(Exception) is open to all legal residents internationally, who are eighteen (18) years of age or older (except in the case of legal residents of certain states where the legal age of majority is greater than eighteen (18) years of age, such legal age of majority) at the time of entry. Employees, officers, and directors (including immediate family members (spouse, parent, child, sibling and their respective spouses, regardless of where they reside) and members of the same household, whether or not related) of Manning ("Sponsor"), and any and all other companies associated with expect(Exception) are not eligible to participate or win a Prize (defined below).</p>
<p><strong>HOW TO ENTER; RANDOM DRAWINGS:</strong> You may enter expect(Exception) in one (1) way: via Twitter. No other method of entry will be accepted. Limit one (1) entry per person/Twitter account/email address/household per Save Entry Period (as defined below), regardless of method of entry. On or about February 9, 2021, a random drawing will be held to select one (1) Grand Prize winner from among all First Prize winners.
<br><br>
To enter via Twitter, you must (a) have a valid, public (i.e., not protected) Twitter account and be a follower of @Yankees and (b) when @Yankees publishes a Sweepstakes-related Tweet which solicits entries ("Original Tweet"), Retweet such Original Tweet with the hashtag #expectException and link another person on Twitter, pursuant to the (i) Content Restrictions (as set forth in the Content Restrictions section below), and (ii) Twitter Terms of Service and Twitter Rules available at www.twitter.com during expect(Exception) Period. All information submitted online via Twitter is subject to, and will be treated in a manner consistent with, Twitter's Privacy Policy accessible at: https://twitter.com/privacy?lang=en and Twitter Terms of Service and Twitter Rules. If you do not have a Twitter account, visit www.twitter.com and register in accordance with the enrolment instructions for a free Twitter account. The time of receipt of any valid Twitter entry shall be the time such valid entry becomes available to Sponsor on Twitter.com. Sponsor's computer shall be the official clock of each Sweepstakes. Any entries that does not comply with the Content Restrictions or otherwise with these Official Rules, are void.</p>
<p><strong>PRIZES</strong>: At least fours (4) Prize will be awarded. Each prize Winner will receive one (1) code for an eBook copy of "Testing JavaScript Applications" from Lucas da Luca, by Manning.</p>
</div>